language: java
install:
  - source ~/virtualenv/python3.6/bin/activate
  - git clone --progress --verbose https://github.com/aniehuser/senior-design-group10.git
  - cd senior-design-group10/scripts
  - ./deploy_python3.sh &
##### TODO:: edit this time after signin/signup route
  - sleep 30s
  - cd ../..
script: mvn test
jdk:
  - openjdk10
  - openjdk11
  - oraclejdk11
